name: Deploy App to Docker and Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Passo 3: Login no DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Passo 4: Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t meu-app:latest .

      # Passo 5: Subir a imagem para o DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker tag meu-app:latest ${{ secrets.DOCKER_USERNAME }}/meu-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/meu-app:latest

      # Passo 6: Conectar via SSH e rodar o container no servidor
      - name: Deploy app to remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/meu-app:latest
            docker run -d -p 8103:8103 --name meu-app ${{ secrets.DOCKER_USERNAME }}/meu-app:latest
